### ISSUE TITLE
Add field 

### ISSUE THREAD

**Issue by gnollet** [promhippie/prometheus-vcd-sd#130]
Hi,
We found you project very interesting but is it possible to add the esx host information on service discovery ?
The json output file doesn't include this interesting information and we would like to supervise when a node move to an other esx host.

Thanks a lot

**Comment by tboerger** [comment]
If the api provides this information it could be easily added, I need to check for this information.

**Comment by tboerger** [comment]
I have not found any information about the used host, feel free to hack on it if you got an idea how to gather this information. Most of the logic starts at https://github.com/promhippie/prometheus-vcd-sd/blob/master/pkg/action/discoverer.go#L171.

**Comment by tboerger** [comment]
Closing this for now, feel free to reopen it if you got a way to get this information.
