### ISSUE TITLE
Invalid network label (because of a space in the network's name)

### ISSUE THREAD

**Issue by mrik974-gig** [promhippie/prometheus-vcd-sd#142]
Hi :)
I'm getting this error :
`go:337 level=error component="discovery manager scrape" discovery=file msg="Error reading file" path=/etc/sd/vcd-vdcplus.json err="\"__meta_vcd_network_network name\" is not a valid label name"`

It seems that a space in any label name is not good for Prometheus. 
I'm not confident in developing in Go but if you don't have time I can take a look at it :)

**Comment by tboerger** [comment]
Hum, haven't seen network names with spaces in it. You could provide a PR which extends this list: https://github.com/promhippie/prometheus-vcd-sd/blob/master/pkg/action/discoverer.go#L284-L288

**Comment by mrik974-gig** [comment]
Thanks @tboerger, it's done. Do I need to update the changelog as well ?

**Comment by tboerger** [comment]
Oh it would be great if you add a new markdown file to changelog/unreleased/, details how to write it you can see within the changelog/ directory.

**Comment by mrik974-gig** [comment]
Thank that was fast and neat ! 💯

**Comment by tboerger** [comment]
I had to fix the formatting, but nevertheless the latest tag should already include this fix.
