### ISSUE TITLE
new tag

### ISSUE THREAD

**Issue by klucsik** [promhippie/prometheus-vcd-sd#189]
Hi, Thank you for the great work, this is a useful tool.
We would like to use fixed tags in our deployment, but the 0.4.0 doesn't include #142 which affects our systems.
Can you create a new release tag?

**Comment by tboerger** [comment]
I totally missed that, there you go: https://github.com/promhippie/prometheus-vcd-sd/releases/tag/v0.4.1

**Comment by klucsik** [comment]
Thank you for your quick response, I tested it now, and working like a charm
