### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by reski-rukmantiyo** [promhippie/prometheus-vcd-sd#20]
Hi, 

Thanks for this wonderful project  not many project at github that can combine vcloud director metrics into prometheus.
But i still wondering how to use it? since, my prometheus can't read any information from output.log. 
It can only read data like this. There's no info in output.log such as __meta_vcd_metadata_apps, __meta_vcd_num_cores_per_socket that listed in vcd-sd result page (http://localhost:9000/metrics)

![image](https://user-images.githubusercontent.com/64754300/113602304-a7284280-966c-11eb-858f-9a0e1f80ed2a.png)
are there any possibilities to read whatever in output.log said into Prometheus, coz output.log data is accurate but somehow can't be injected into vcd-sd metrics data (http://localhost:9000/metrics)

Thanks

**Comment by tboerger** [comment]
The metrics of this tool are only related to this tool, it doesn't include any vcloud metrics. This is meant to provide a dynamic inventory of the virtual machines launched on vcloud director.

**Comment by reski-rukmantiyo** [comment]
noted on this. Thanks
